# Makefile for workqueue sample module

obj-$(CONFIG_SAMPLE_WAITQUEUE) += waitqueue_sample.o
obj-$(CONFIG_SAMPLE_WAITQUEUE) += waitqueue_exclusive_sample.o
obj-$(CONFIG_SAMPLE_WAITQUEUE) += wait_bit_queue_sample.o
