# Makefile for Linux samples code

obj-$(CONFIG_SAMPLES)	+= kobject/ kprobes/ trace_events/ livepatch/ \
			   hw_breakpoint/ kfifo/ kdb/ hidraw/ rpmsg/ seccomp/ configfs/ \
			   hello_world/		\
			   workqueue/		\
			   delayed_work_race/	\
			   netlink/		\
			   waitqueue/		\
			   proc/
